data:
  batch_size: 4
  img_size: 96
  pin_memory: True
  num_workers: 8
  path: 'fault_detection/datasets/finetune/200-20/'
  json_path: 'datasets'
  json_name: 'dataset.json'

model:
  name: 'UNET3'
  in_chans: 1
  num_classes: 1
  ds: False
  drop: 0.
  attn_drop: 0.
  drop_path: 0.
  resume: ''

train:
  amp: True
  start_epoch: 0
  epochs: 200
  clip_grad: True
  auto_resume: True
  patience: 200
  output: 'output'
  save_freq: 100
  print_freq: 10
  seed: 20240629

lr_scheduler:
  name: 'cosine'
  warmup_epochs: 10
  min_lr: 6e-6

optimizer:
  name: 'adamw'
  betas: [0.9, 0.999]
  eps: 1e-8
  momentum: 0.9
  lr: 2e-3
  weight_decay: 1e-2

loss:
  name: 'dice_focal'

aug:
  mixup: True
  lambdaa: 0.2

wandb: True

gpu: '0,1'

gpu_num: s